name: Python package testing

on: push

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: update pip
        run: |
          python -m pip install --upgrade pip
      - name: install vlinder_toolkit
        run: pip3 install --index-url https://test.pypi.org/simple/ --extra-index-url https://pypi.org/simple vlinder_toolkit --upgrade
      - name: check toolkit version
        run: pip3 show vlinder_toolkit
      - name: run import test
        run: python3 tests/basic_import_test.py
    - name: Running examples as tests
      run: |
        python3 examples/introduction_example.py
        #python3 examples/lcz_example.py
        #python3 examples/plotting_example.py